// Demo dataset. Brands, products, prices and ratings are fictional sample
// values (plan §6.1). Copy is Rioplatense Spanish, written to be read by the
// client: every field is something a skincare advisor would actually say.

export type Suitability = 'IDEAL' | 'SUITABLE' | 'CAUTION' | 'NOT_RECOMMENDED'
export type StepType = 'CLEANSER' | 'TONER' | 'EXFOLIANT' | 'SERUM' | 'TREATMENT' | 'MOISTURIZER' | 'SUNSCREEN'
export type Moment = 'AM' | 'PM' | 'BOTH'

export const brands = [
  { slug: 'aurea-lab', name: 'Aurea Lab' },
  { slug: 'nube-skin', name: 'Nube Skin' },
  { slug: 'mar-de-sal', name: 'Mar de Sal' },
  { slug: 'verde-raiz', name: 'Verde Raíz' },
  { slug: 'clara-botanica', name: 'Clara Botánica' },
] as const

export const skinTypes = [
  { slug: 'seca', name: 'Seca' },
  { slug: 'grasa', name: 'Grasa' },
  { slug: 'mixta', name: 'Mixta' },
  { slug: 'normal', name: 'Normal' },
  { slug: 'sensible', name: 'Sensible' },
] as const

export const concerns = [
  { slug: 'acne', name: 'Acné y granitos', shortLabel: 'Acné', description: 'Granitos que aparecen seguido o puntos negros que no se van.' },
  { slug: 'manchas', name: 'Manchas y tono desparejo', shortLabel: 'Manchas', description: 'Manchas de sol, marcas de granitos o un tono que no es parejo.' },
  { slug: 'deshidratacion', name: 'Deshidratación', shortLabel: 'Hidratación', description: 'Piel tirante u opaca, con líneas que aparecen cuando le falta agua.' },
  { slug: 'sensibilidad', name: 'Rojeces y sensibilidad', shortLabel: 'Rojeces', description: 'Rojeces, ardor o una piel que reacciona a los productos nuevos.' },
  { slug: 'lineas', name: 'Líneas finas', shortLabel: 'Líneas finas', description: 'Primeras líneas de expresión y pérdida de firmeza.' },
  { slug: 'poros', name: 'Poros y brillo', shortLabel: 'Poros', description: 'Poros visibles y brillo en la zona T a lo largo del día.' },
] as const

type SeedIngredient = {
  slug: string
  commonName: string
  inciName: string
  isKeyActive: boolean
  isIrritant: boolean
  description: string | null
}

// The 18 ingredients of the plan, plus the base ingredients a real INCI list
// needs. Base ingredients are never key actives and never irritants.
export const ingredients: SeedIngredient[] = [
  { slug: 'niacinamida', commonName: 'Niacinamida', inciName: 'Niacinamide', isKeyActive: true, isIrritant: false, description: 'Vitamina B3. Regula el sebo, afina la apariencia de los poros y ayuda a emparejar el tono. Es de los activos mejor tolerados, por eso entra en casi cualquier rutina.' },
  { slug: 'acido-hialuronico', commonName: 'Ácido hialurónico', inciName: 'Sodium Hyaluronate', isKeyActive: true, isIrritant: false, description: 'Retiene agua en la superficie de la piel. Da una hidratación inmediata y un aspecto más jugoso, sin sumar grasa.' },
  { slug: 'acido-salicilico', commonName: 'Ácido salicílico', inciName: 'Salicylic Acid', isKeyActive: true, isIrritant: true, description: 'Un BHA que se disuelve en la grasa: entra en el poro y lo destapa desde adentro. Es el activo de referencia para granitos y puntos negros.' },
  { slug: 'acido-glicolico', commonName: 'Ácido glicólico', inciName: 'Glycolic Acid', isKeyActive: true, isIrritant: true, description: 'Un AHA de molécula chica. Afloja las células muertas de la superficie, mejora la textura y, con el uso sostenido, ayuda a aclarar manchas.' },
  { slug: 'retinol', commonName: 'Retinol', inciName: 'Retinol', isKeyActive: true, isIrritant: true, description: 'Derivado de la vitamina A. Acelera la renovación de la piel y estimula el colágeno. Es el activo con más evidencia para líneas finas y pide paciencia: los resultados se ven desde las 8 semanas.' },
  { slug: 'vitamina-c', commonName: 'Vitamina C', inciName: 'Ascorbic Acid', isKeyActive: true, isIrritant: true, description: 'Antioxidante que neutraliza el daño del sol y la contaminación, y aclara manchas de a poco. Rinde mejor de día, debajo del protector solar.' },
  { slug: 'ceramidas', commonName: 'Ceramidas', inciName: 'Ceramide NP', isKeyActive: true, isIrritant: false, description: 'Lípidos que forman parte de la barrera natural de la piel. Reponerlos reduce la pérdida de agua y la sensación de tirantez.' },
  { slug: 'centella', commonName: 'Centella asiática', inciName: 'Centella Asiatica Extract', isKeyActive: true, isIrritant: false, description: 'Extracto vegetal calmante. Baja las rojeces y acompaña la recuperación de la barrera cuando la piel está reactiva.' },
  { slug: 'pantenol', commonName: 'Pantenol', inciName: 'Panthenol', isKeyActive: true, isIrritant: false, description: 'Provitamina B5. Hidrata, calma y ayuda a reparar. Suaviza la sensación de la piel irritada.' },
  { slug: 'zinc-pca', commonName: 'Zinc PCA', inciName: 'Zinc PCA', isKeyActive: true, isIrritant: false, description: 'Regula la producción de sebo y tiene un leve efecto antibacteriano. Suma muy bien con la niacinamida.' },
  { slug: 'azelaico', commonName: 'Ácido azelaico', inciName: 'Azelaic Acid', isKeyActive: true, isIrritant: false, description: 'Trabaja a la vez sobre granitos, rojeces y manchas. Es de los pocos activos de ese perfil que suele tolerar la piel sensible.' },
  { slug: 'peptidos', commonName: 'Péptidos', inciName: 'Palmitoyl Tripeptide-1', isKeyActive: true, isIrritant: false, description: 'Cadenas cortas de aminoácidos que le indican a la piel que produzca colágeno. Mejoran la firmeza de a poco y sin irritar.' },
  { slug: 'escualano', commonName: 'Escualano', inciName: 'Squalane', isKeyActive: true, isIrritant: false, description: 'Un aceite liviano, muy parecido al sebo propio de la piel. Nutre sin sensación grasa y amortigua activos fuertes como el retinol.' },
  { slug: 'glicerina', commonName: 'Glicerina', inciName: 'Glycerin', isKeyActive: false, isIrritant: false, description: 'Humectante clásico: atrae agua hacia la piel y la retiene. Simple, barato y de los que mejor funcionan.' },
  { slug: 'arcilla', commonName: 'Arcilla caolín', inciName: 'Kaolin', isKeyActive: false, isIrritant: false, description: 'Arcilla blanca que absorbe el exceso de sebo y las impurezas. Es la más suave de las arcillas y no deja la piel tirante.' },
  { slug: 'alantoina', commonName: 'Alantoína', inciName: 'Allantoin', isKeyActive: false, isIrritant: false, description: 'Calma y suaviza la piel. Acompaña a los activos fuertes para que se toleren mejor.' },
  { slug: 'filtros-uv', commonName: 'Filtros UV', inciName: '(varios)', isKeyActive: true, isIrritant: false, description: 'Filtros de amplio espectro que protegen de la radiación UVA, que mancha y envejece, y de la UVB, que quema.' },
  { slug: 'agua', commonName: 'Agua', inciName: 'Aqua', isKeyActive: false, isIrritant: false, description: null },

  { slug: 'butilenglicol', commonName: 'Butilenglicol', inciName: 'Butylene Glycol', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'propanodiol', commonName: 'Propanodiol', inciName: 'Propanediol', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'pentilenglicol', commonName: 'Pentilenglicol', inciName: 'Pentylene Glycol', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'goma-xantana', commonName: 'Goma xantana', inciName: 'Xanthan Gum', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'carbomero', commonName: 'Carbómero', inciName: 'Carbomer', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'fenoxietanol', commonName: 'Fenoxietanol', inciName: 'Phenoxyethanol', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'etilhexilglicerina', commonName: 'Etilhexilglicerina', inciName: 'Ethylhexylglycerin', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'cocamidopropil-betaina', commonName: 'Cocamidopropil betaína', inciName: 'Cocamidopropyl Betaine', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'cocoil-glicinato', commonName: 'Cocoil glicinato de sodio', inciName: 'Sodium Cocoyl Glycinate', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'alcohol-cetearilico', commonName: 'Alcohol cetearílico', inciName: 'Cetearyl Alcohol', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'trigliceridos', commonName: 'Triglicéridos', inciName: 'Caprylic/Capric Triglyceride', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'manteca-karite', commonName: 'Manteca de karité', inciName: 'Butyrospermum Parkii Butter', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'colesterol', commonName: 'Colesterol', inciName: 'Cholesterol', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'tocoferol', commonName: 'Vitamina E', inciName: 'Tocopherol', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'acido-ferulico', commonName: 'Ácido ferúlico', inciName: 'Ferulic Acid', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'bisabolol', commonName: 'Bisabolol', inciName: 'Bisabolol', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'hidroxido-sodio', commonName: 'Hidróxido de sodio', inciName: 'Sodium Hydroxide', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'oxido-zinc', commonName: 'Óxido de zinc', inciName: 'Zinc Oxide', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'dioxido-titanio', commonName: 'Dióxido de titanio', inciName: 'Titanium Dioxide', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'bemotrizinol', commonName: 'Bemotrizinol', inciName: 'Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'etilhexil-triazona', commonName: 'Etilhexil triazona', inciName: 'Ethylhexyl Triazone', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'dhhb', commonName: 'DHHB', inciName: 'Diethylamino Hydroxybenzoyl Hexyl Benzoate', isKeyActive: false, isIrritant: false, description: null },
  { slug: 'oxido-hierro', commonName: 'Óxidos de hierro', inciName: 'CI 77491, CI 77492', isKeyActive: false, isIrritant: false, description: null },
]

export const conflicts = [
  { a: 'retinol', b: 'acido-glicolico', severity: 'ALTERNATE_DAYS', note: 'Juntos pueden irritar. Se usan en noches alternas.' },
  { a: 'retinol', b: 'vitamina-c', severity: 'CAUTION', note: 'Mejor la vitamina C de día y el retinol de noche.' },
] as const

// INCI entry: an ingredient slug, or [slug, { key, conc }] for key actives.
type Inci = string | [string, { key?: boolean; conc?: string }]

export type SeedProduct = {
  slug: string
  name: string
  brand: (typeof brands)[number]['slug']
  stepType: StepType
  moment: Moment
  sizeLabel: string
  priceCents: number
  color: string
  avgRating: number
  reviewCount: number
  ideal: string[]
  notRecommended: string[]
  concerns: Record<string, number>
  inci: Inci[]
  texture: string
  fragranceFree: boolean
  shortDescription: string
  description: string
  whyWeChose: string
  ourRating: number
  ratingNotes: string
  howToUse: string
  precautions: string
}

const ALL = ['seca', 'grasa', 'mixta', 'normal', 'sensible']
const ars = (pesos: number) => pesos * 100

export const products: SeedProduct[] = [
  {
    slug: 'gel-limpiador-purificante',
    name: 'Gel limpiador purificante',
    brand: 'mar-de-sal',
    stepType: 'CLEANSER',
    moment: 'BOTH',
    sizeLabel: '200 ml',
    priceCents: ars(14_900),
    color: '#D6E3DC',
    avgRating: 4.5,
    reviewCount: 212,
    ideal: ['grasa', 'mixta'],
    notRecommended: ['seca', 'sensible'],
    concerns: { acne: 70, poros: 80 },
    inci: ['agua', 'cocamidopropil-betaina', 'cocoil-glicinato', 'glicerina', ['acido-salicilico', { key: true, conc: '0,5%' }], ['zinc-pca', { key: true }], 'pantenol', 'goma-xantana', 'fenoxietanol'],
    texture: 'Gel transparente',
    fragranceFree: true,
    shortDescription: 'Gel de limpieza diaria con ácido salicílico suave, para piel grasa y con tendencia a granitos.',
    description: 'Limpia el exceso de sebo sin dejar la piel tirante. El ácido salicílico al 0,5% trabaja dentro del poro en cada lavado y el zinc PCA ayuda a controlar el brillo durante el día. Hace poca espuma y se enjuaga fácil.',
    whyWeChose: 'Buscábamos un limpiador para piel grasa que no fuera agresivo. La mayoría de los geles "anti-acné" resecan tanto que la piel responde con más sebo. Este mantiene el equilibrio: limpia a fondo y la piel queda cómoda.',
    ourRating: 86,
    ratingNotes: 'Muy buen control del brillo y una concentración de salicílico justa para el uso diario. Le restamos puntos porque puede resultar seco en invierno o en mejillas normales, y porque solo no alcanza para tratar granitos activos.',
    howToUse: 'Mañana y noche, sobre la piel húmeda. Masajeá una cantidad del tamaño de una avellana durante 30 segundos, insistiendo en la zona T, y enjuagá con agua tibia.',
    precautions: 'No lo uses sobre piel irritada o con heridas. Si sentís tirantez, usalo solo de noche y a la mañana lavate con agua.',
  },
  {
    slug: 'crema-limpiadora-suave',
    name: 'Crema limpiadora suave',
    brand: 'clara-botanica',
    stepType: 'CLEANSER',
    moment: 'BOTH',
    sizeLabel: '150 ml',
    priceCents: ars(13_500),
    color: '#EDE4D6',
    avgRating: 4.7,
    reviewCount: 184,
    ideal: ['seca', 'sensible', 'normal'],
    notRecommended: [],
    concerns: { sensibilidad: 60, deshidratacion: 50 },
    inci: ['agua', ['glicerina', { key: true }], 'trigliceridos', 'alcohol-cetearilico', ['ceramidas', { key: true }], 'colesterol', 'pantenol', 'goma-xantana', 'fenoxietanol', 'etilhexilglicerina'],
    texture: 'Crema fluida',
    fragranceFree: true,
    shortDescription: 'Limpiador cremoso, sin espuma, que respeta la barrera de la piel seca y sensible.',
    description: 'Una crema que limpia y desmaquilla sin detergentes fuertes. Las ceramidas y la glicerina reponen lo que el lavado se lleva, así que la piel queda suave, no tirante. Se retira con agua o con un algodón húmedo.',
    whyWeChose: 'Es el limpiador que recomendaríamos a cualquiera que sienta la cara "como de papel" después de lavarla. Pocas fórmulas logran sacar bien el protector y el maquillaje liviano sin resecar; esta sí.',
    ourRating: 91,
    ratingNotes: 'Excelente tolerancia, fórmula corta y sin fragancia, y rinde mucho. El punto flojo: en piel muy grasa puede dejar una sensación de película, y no alcanza para maquillaje a prueba de agua.',
    howToUse: 'Mañana y noche. Aplicá sobre la piel seca o apenas húmeda, masajeá un minuto y retirá con agua tibia. De noche, si usaste maquillaje, repetí el paso.',
    precautions: 'Para maquillaje a prueba de agua, usá antes un desmaquillante bifásico.',
  },
  {
    slug: 'espuma-limpiadora-equilibrante',
    name: 'Espuma limpiadora equilibrante',
    brand: 'nube-skin',
    stepType: 'CLEANSER',
    moment: 'BOTH',
    sizeLabel: '150 ml',
    priceCents: ars(12_800),
    color: '#DCE5EE',
    avgRating: 4.4,
    reviewCount: 96,
    ideal: ['mixta', 'normal'],
    notRecommended: [],
    concerns: { poros: 50 },
    inci: ['agua', 'cocoil-glicinato', 'glicerina', ['niacinamida', { key: true }], ['pantenol', { key: true }], 'alantoina', 'fenoxietanol', 'etilhexilglicerina'],
    texture: 'Espuma aireada',
    fragranceFree: true,
    shortDescription: 'Espuma liviana que limpia la zona T sin resecar las mejillas.',
    description: 'Sale del envase ya convertida en espuma, así que no hace falta frotar. La niacinamida ayuda a equilibrar el sebo y el pantenol mantiene la piel cómoda. Pensada para pieles mixtas que necesitan limpiar bien la frente y la nariz sin castigar el resto.',
    whyWeChose: 'La piel mixta tiene un problema: lo que sirve para la zona T suele ser demasiado para las mejillas. Esta espuma encuentra el punto medio, y la textura la hace agradable de usar todos los días.',
    ourRating: 84,
    ratingNotes: 'Muy agradable de usar y bien equilibrada para piel mixta y normal. Pierde puntos por el rendimiento, porque el envase de espuma se termina rápido, y porque en piel muy grasa se queda corta.',
    howToUse: 'Mañana y noche. Dos o tres pulsaciones en las manos, aplicá sobre la cara húmeda con movimientos suaves y enjuagá.',
    precautions: 'Evitá el contacto con los ojos. Si de noche no alcanza para sacar el protector o el maquillaje, hacé una doble limpieza.',
  },
  {
    slug: 'tonico-hidratante',
    name: 'Tónico hidratante',
    brand: 'nube-skin',
    stepType: 'TONER',
    moment: 'BOTH',
    sizeLabel: '200 ml',
    priceCents: ars(15_200),
    color: '#E4DFEC',
    avgRating: 4.6,
    reviewCount: 158,
    ideal: ALL,
    notRecommended: [],
    concerns: { deshidratacion: 80 },
    inci: ['agua', 'glicerina', 'butilenglicol', ['acido-hialuronico', { key: true }], ['pantenol', { key: true }], 'alantoina', 'fenoxietanol', 'etilhexilglicerina'],
    texture: 'Líquido acuoso',
    fragranceFree: true,
    shortDescription: 'Tónico sin alcohol, con ácido hialurónico, que prepara la piel para el resto de la rutina.',
    description: 'Más que un tónico astringente, es una primera capa de hidratación. El ácido hialurónico y el pantenol dejan la piel húmeda y receptiva, y eso ayuda a que el sérum y la crema se distribuyan mejor. No tiene alcohol ni fragancia.',
    whyWeChose: 'Sirve para todas las pieles, y eso es raro. Las secas lo notan como un alivio inmediato y las grasas agradecen hidratarse sin sumar grasa. Es el paso más fácil de agregar cuando alguien quiere pasar de tres a cinco pasos.',
    ourRating: 88,
    ratingNotes: 'Fórmula simple, bien tolerada y versátil. No hace milagros por sí solo, y no pretende hacerlos: su valor está en mejorar cómo funciona el resto de la rutina.',
    howToUse: 'Después de limpiar, poné unas gotas en las palmas y presioná sobre la cara. Si tenés la piel muy deshidratada, repetí una segunda capa. Seguí con el sérum mientras la piel todavía está húmeda.',
    precautions: 'Sin precauciones particulares. Como con cualquier producto nuevo, probalo primero en una zona chica.',
  },
  {
    slug: 'tonico-calmante-centella',
    name: 'Tónico calmante de centella',
    brand: 'verde-raiz',
    stepType: 'TONER',
    moment: 'BOTH',
    sizeLabel: '200 ml',
    priceCents: ars(16_400),
    color: '#DDE3D3',
    avgRating: 4.8,
    reviewCount: 131,
    ideal: ['sensible', 'seca'],
    notRecommended: [],
    concerns: { sensibilidad: 90 },
    inci: ['agua', ['centella', { key: true }], 'glicerina', 'propanodiol', ['alantoina', { key: true }], 'pantenol', 'bisabolol', 'fenoxietanol'],
    texture: 'Líquido acuoso',
    fragranceFree: true,
    shortDescription: 'Tónico calmante con centella asiática, para pieles que se enrojecen con facilidad.',
    description: 'Baja la temperatura de la piel, en la sensación y a la vista. La centella y la alantoína calman las rojeces y acompañan la recuperación de la barrera, sin ningún activo que pueda sensibilizar. Ideal para los días en que la piel está reactiva.',
    whyWeChose: 'Nos pidieron muchas veces algo "para cuando la piel está brava". Este tónico es la respuesta: no promete tratar nada, promete no molestar y calmar. En piel sensible, eso vale más que cualquier activo de moda.',
    ourRating: 90,
    ratingNotes: 'Muy bien tolerado; el alivio se nota desde la primera aplicación. Es un producto de cuidado, no de tratamiento: si buscás resultados sobre manchas o granitos, tiene que ir acompañado.',
    howToUse: 'Mañana y noche, después de limpiar. Aplicalo con las manos, o empapá un disco de algodón y dejalo apoyado un minuto sobre las zonas con rojeces.',
    precautions: 'Si tenés una rosácea diagnosticada, consultá con tu dermatólogo antes de sumar productos nuevos.',
  },
  {
    slug: 'exfoliante-liquido-aha-7',
    name: 'Exfoliante líquido AHA 7%',
    brand: 'aurea-lab',
    stepType: 'EXFOLIANT',
    moment: 'PM',
    sizeLabel: '100 ml',
    priceCents: ars(19_800),
    color: '#F0DFD0',
    avgRating: 4.5,
    reviewCount: 176,
    ideal: ['normal', 'mixta', 'grasa'],
    notRecommended: ['sensible'],
    concerns: { manchas: 70, poros: 50, lineas: 40 },
    inci: ['agua', ['acido-glicolico', { key: true, conc: '7%' }], 'hidroxido-sodio', 'glicerina', 'propanodiol', 'alantoina', 'fenoxietanol', 'etilhexilglicerina'],
    texture: 'Líquido transparente',
    fragranceFree: true,
    shortDescription: 'Exfoliante con ácido glicólico al 7% que mejora la textura y empareja el tono.',
    description: 'Un exfoliante químico que se aplica con las manos y no se enjuaga. El ácido glicólico afloja las células muertas de la superficie: la piel queda más lisa y luminosa, y con el uso sostenido las manchas se aclaran. Se usa de noche, dos o tres veces por semana.',
    whyWeChose: 'La concentración está pensada para que alguien que nunca usó ácidos pueda empezar sin miedo, y que igual vea resultados en un mes. Cambia la textura de la piel más que casi cualquier otro paso.',
    ourRating: 87,
    ratingNotes: 'Resultados visibles en textura y luminosidad en pocas semanas. Le restamos puntos porque exige constancia con el protector solar y porque no es apto para piel sensible.',
    howToUse: 'De noche, dos o tres veces por semana. Después de limpiar, con la piel seca, aplicá unas gotas con las manos sobre toda la cara, evitando el contorno de ojos. Esperá un minuto y seguí con tu crema.',
    precautions: 'Aumenta la sensibilidad al sol: al día siguiente, el protector solar es obligatorio. No lo uses la misma noche que el retinol. Puede picar un poco las primeras veces.',
  },
  {
    slug: 'exfoliante-bha-2',
    name: 'Exfoliante BHA 2%',
    brand: 'mar-de-sal',
    stepType: 'EXFOLIANT',
    moment: 'PM',
    sizeLabel: '120 ml',
    priceCents: ars(19_500),
    color: '#D9DFE6',
    avgRating: 4.7,
    reviewCount: 342,
    ideal: ['grasa', 'mixta'],
    notRecommended: ['seca', 'sensible'],
    concerns: { acne: 90, poros: 90 },
    inci: ['agua', 'butilenglicol', ['acido-salicilico', { key: true, conc: '2%' }], 'glicerina', 'alantoina', 'goma-xantana', 'fenoxietanol'],
    texture: 'Líquido liviano',
    fragranceFree: true,
    shortDescription: 'Exfoliante con ácido salicílico al 2% que destapa los poros y previene los granitos.',
    description: 'El ácido salicílico se disuelve en la grasa, entra en el poro y lo limpia desde adentro. Con el uso regular se reducen los puntos negros, los poros se ven más chicos y los granitos aparecen menos seguido. Textura líquida y liviana, sin enjuague.',
    whyWeChose: 'Si tuviéramos que elegir un solo producto para piel grasa con granitos, sería este. El 2% es la concentración con más respaldo, y la base liviana no deja residuo.',
    ourRating: 92,
    ratingNotes: 'El producto con mejor relación entre resultado y tolerancia para poros y granitos. No es para piel seca ni sensible, y los primeros días puede haber una pequeña "purga" antes de mejorar.',
    howToUse: 'De noche, dos o tres veces por semana al principio; si la piel lo tolera bien, podés pasar a noche por medio. Aplicá con un algodón o con las manos sobre la piel limpia y seca, sin enjuagar.',
    precautions: 'Usá protector solar al día siguiente. No lo combines la misma noche con otros exfoliantes. Si estás embarazada, consultá antes con tu médico.',
  },
  {
    slug: 'serum-niacinamida-10-zinc',
    name: 'Sérum niacinamida 10% + zinc',
    brand: 'aurea-lab',
    stepType: 'SERUM',
    moment: 'BOTH',
    sizeLabel: '30 ml',
    priceCents: ars(18_900),
    color: '#E3E0DB',
    avgRating: 4.6,
    reviewCount: 408,
    ideal: ['grasa', 'mixta'],
    notRecommended: [],
    concerns: { poros: 90, acne: 70, manchas: 50 },
    inci: ['agua', ['niacinamida', { key: true, conc: '10%' }], ['zinc-pca', { key: true, conc: '1%' }], 'pentilenglicol', 'goma-xantana', 'fenoxietanol', 'etilhexilglicerina'],
    texture: 'Sérum acuoso',
    fragranceFree: true,
    shortDescription: 'Sérum de niacinamida al 10% y zinc para poros, brillo y marcas de granitos.',
    description: 'Una fórmula concentrada que trabaja sobre tres frentes: regula el sebo, afina la apariencia de los poros y ayuda a emparejar el tono, incluidas las marcas que dejan los granitos. Se absorbe rápido y no deja película.',
    whyWeChose: 'La niacinamida es de los activos con mejor relación entre efecto y tolerancia. Este sérum la combina con zinc en una concentración que se nota, a un precio que permite usarlo todos los días.',
    ourRating: 89,
    ratingNotes: 'Control del brillo visible en dos o tres semanas y muy buena tolerancia. Si se aplica mucha cantidad, algunas pieles notan una textura un poco pegajosa; con tres gotas alcanza.',
    howToUse: 'Mañana y noche, después del tónico y antes de la crema. Tres gotas para toda la cara, distribuidas con toques suaves.',
    precautions: 'Si al poner la crema encima se forman grumitos, esperá un minuto más antes del paso siguiente. Si notás enrojecimiento, no lo apliques junto con vitamina C pura.',
  },
  {
    slug: 'serum-vitamina-c-15',
    name: 'Sérum vitamina C 15%',
    brand: 'aurea-lab',
    stepType: 'SERUM',
    moment: 'AM',
    sizeLabel: '30 ml',
    priceCents: ars(26_500),
    color: '#F1DEC2',
    avgRating: 4.4,
    reviewCount: 267,
    ideal: ['normal', 'mixta', 'seca'],
    notRecommended: ['sensible'],
    concerns: { manchas: 90, lineas: 50 },
    inci: ['agua', ['vitamina-c', { key: true, conc: '15%' }], 'propanodiol', 'glicerina', 'tocoferol', 'acido-ferulico', 'hidroxido-sodio', 'fenoxietanol'],
    texture: 'Sérum fluido',
    fragranceFree: true,
    shortDescription: 'Sérum antioxidante de vitamina C al 15% para manchas y luminosidad.',
    description: 'Vitamina C pura en una concentración eficaz, en un frasco ámbar que la protege de la luz. De día neutraliza el daño que provocan el sol y la contaminación; con el uso sostenido, aclara manchas y le devuelve luz a la piel. Funciona mejor debajo del protector solar.',
    whyWeChose: 'Es el sérum de mañana por excelencia para manchas. Elegimos esta fórmula porque combina el ácido ascórbico con vitamina E y ácido ferúlico, que lo estabilizan y potencian su efecto.',
    ourRating: 85,
    ratingNotes: 'Resultados claros en luminosidad y tono. Pierde puntos porque se oxida si no se guarda bien cerrado, y porque en piel sensible puede picar.',
    howToUse: 'Solo de mañana. Después de limpiar, aplicá cuatro o cinco gotas sobre la piel seca, esperá un minuto y seguí con la crema y el protector solar.',
    precautions: 'Guardalo bien cerrado y lejos del calor. Si toma un color marrón oscuro, se oxidó y perdió eficacia. No lo uses junto con el retinol: vitamina C de día, retinol de noche.',
  },
  {
    slug: 'serum-acido-hialuronico',
    name: 'Sérum ácido hialurónico',
    brand: 'nube-skin',
    stepType: 'SERUM',
    moment: 'BOTH',
    sizeLabel: '30 ml',
    priceCents: ars(17_900),
    color: '#DDE8EE',
    avgRating: 4.7,
    reviewCount: 389,
    ideal: ALL,
    notRecommended: [],
    concerns: { deshidratacion: 95 },
    inci: ['agua', 'glicerina', ['acido-hialuronico', { key: true }], ['pantenol', { key: true }], 'propanodiol', 'carbomero', 'fenoxietanol', 'etilhexilglicerina'],
    texture: 'Gel acuoso',
    fragranceFree: true,
    shortDescription: 'Sérum hidratante con ácido hialurónico, para todo tipo de piel.',
    description: 'Retiene agua en la superficie de la piel y la deja visiblemente más jugosa en minutos. El pantenol, además, calma la tirantez. Es liviano, no engrasa y se lleva bien con cualquier otro activo.',
    whyWeChose: 'La deshidratación le pasa a todas las pieles, incluso a las grasas. Este sérum es el comodín de la rutina: suma hidratación sin interferir con nada.',
    ourRating: 90,
    ratingNotes: 'Efecto inmediato y excelente compatibilidad. La hidratación es de superficie: en piel muy seca necesita una crema encima para que dure todo el día.',
    howToUse: 'Mañana y noche, sobre la piel todavía húmeda del tónico. Dos o tres gotas, y sellá siempre con una crema.',
    precautions: 'En climas muy secos, aplicalo siempre sobre la piel húmeda y con crema encima; si no, puede dar sensación de tirantez.',
  },
  {
    slug: 'serum-acido-azelaico-10',
    name: 'Sérum ácido azelaico 10%',
    brand: 'clara-botanica',
    stepType: 'SERUM',
    moment: 'BOTH',
    sizeLabel: '30 ml',
    priceCents: ars(22_300),
    color: '#F0DCD8',
    avgRating: 4.5,
    reviewCount: 143,
    ideal: ['sensible', 'grasa', 'mixta'],
    notRecommended: [],
    concerns: { sensibilidad: 70, manchas: 70, acne: 60 },
    inci: ['agua', ['azelaico', { key: true, conc: '10%' }], 'propanodiol', 'trigliceridos', 'alcohol-cetearilico', 'bisabolol', 'goma-xantana', 'fenoxietanol'],
    texture: 'Crema gel',
    fragranceFree: true,
    shortDescription: 'Sérum de ácido azelaico al 10% para rojeces, manchas y granitos. Apto para piel sensible.',
    description: 'El ácido azelaico trabaja a la vez sobre tres problemas que suelen venir juntos: granitos, rojeces y manchas. Es suave, se puede usar de mañana y de noche, y lo toleran bien incluso las pieles que reaccionan a todo.',
    whyWeChose: 'Cuando la piel es sensible pero tiene granitos o manchas, las opciones se achican mucho. Este es el activo que usamos para abrir esa puerta, en una textura de crema gel que no reseca.',
    ourRating: 88,
    ratingNotes: 'Muy buen equilibrio entre eficacia y tolerancia. Los resultados son graduales, de seis a ocho semanas, y las primeras aplicaciones pueden dar un leve cosquilleo que después desaparece.',
    howToUse: 'Una o dos veces por día, después del tónico. Aplicá una capa fina sobre toda la cara o solo en las zonas con rojeces o manchas, y seguí con la crema.',
    precautions: 'Un leve cosquilleo durante las primeras semanas es normal. Si se transforma en ardor persistente, bajá a una aplicación por día.',
  },
  {
    slug: 'retinol-03-escualano',
    name: 'Retinol 0.3% en escualano',
    brand: 'verde-raiz',
    stepType: 'TREATMENT',
    moment: 'PM',
    sizeLabel: '30 ml',
    priceCents: ars(27_900),
    color: '#DED6E0',
    avgRating: 4.6,
    reviewCount: 221,
    ideal: ['normal', 'mixta', 'seca'],
    notRecommended: ['sensible'],
    concerns: { lineas: 95, manchas: 60, acne: 50 },
    inci: [['escualano', { key: true }], 'trigliceridos', ['retinol', { key: true, conc: '0,3%' }], 'tocoferol', 'bisabolol'],
    texture: 'Aceite seco',
    fragranceFree: true,
    shortDescription: 'Retinol al 0,3% en una base de escualano, para líneas finas y textura.',
    description: 'El activo con más evidencia para líneas finas y textura, en una concentración de inicio y disuelto en escualano, un aceite liviano que amortigua la irritación. Acelera la renovación de la piel y estimula el colágeno. Los resultados empiezan a verse a partir de las 8 semanas.',
    whyWeChose: 'Queríamos un retinol para empezar bien: suficiente para ver resultados, y lo bastante suave para no tener que abandonarlo a la semana. La base de aceite hace que la piel lo tolere mucho mejor que en un sérum acuoso.',
    ourRating: 93,
    ratingNotes: 'La mejor puerta de entrada al retinol que probamos. No es apto para piel sensible ni durante el embarazo, y exige paciencia y protector solar todos los días.',
    howToUse: 'Solo de noche. Empezá con dos noches por semana y, si la piel lo tolera, aumentá de a poco hasta llegar a noche por medio. Dos o tres gotas sobre la piel limpia y seca, y después tu crema.',
    precautions: 'No lo uses durante el embarazo ni la lactancia. Usá protector solar todos los días. No lo combines la misma noche con ácidos exfoliantes (AHA o BHA), y dejá la vitamina C para la mañana.',
  },
  {
    slug: 'gel-crema-ligero',
    name: 'Gel crema ligero',
    brand: 'nube-skin',
    stepType: 'MOISTURIZER',
    moment: 'BOTH',
    sizeLabel: '50 ml',
    priceCents: ars(16_800),
    color: '#DCEAE2',
    avgRating: 4.6,
    reviewCount: 254,
    ideal: ['grasa', 'mixta'],
    notRecommended: [],
    concerns: { deshidratacion: 60, poros: 40 },
    inci: ['agua', 'glicerina', ['niacinamida', { key: true }], ['acido-hialuronico', { key: true }], 'propanodiol', 'carbomero', 'alantoina', 'fenoxietanol', 'etilhexilglicerina'],
    texture: 'Gel crema',
    fragranceFree: true,
    shortDescription: 'Hidratante en gel que no engrasa, para piel mixta y grasa.',
    description: 'Hidrata como una crema y se siente como un gel. La niacinamida ayuda a controlar el brillo y el ácido hialurónico retiene la hidratación, sin dejar la piel pesada. Funciona muy bien como base de maquillaje.',
    whyWeChose: 'Mucha gente con piel grasa se saltea la crema porque todas le parecen pesadas, y termina con la piel deshidratada y más brillante. Este gel crema resuelve esa objeción.',
    ourRating: 87,
    ratingNotes: 'Textura excelente y buena hidratación para piel grasa y mixta. En piel seca, o en pleno invierno, se queda corta.',
    howToUse: 'Mañana y noche, como último paso antes del protector solar. Con una cantidad del tamaño de una arveja alcanza para toda la cara.',
    precautions: 'Si tenés la piel seca, probablemente necesites una crema más nutritiva, al menos de noche.',
  },
  {
    slug: 'crema-reparadora-barrera',
    name: 'Crema reparadora de barrera',
    brand: 'clara-botanica',
    stepType: 'MOISTURIZER',
    moment: 'BOTH',
    sizeLabel: '50 ml',
    priceCents: ars(18_400),
    color: '#E9DFD2',
    avgRating: 4.8,
    reviewCount: 297,
    ideal: ['seca', 'sensible'],
    notRecommended: ['grasa'],
    concerns: { sensibilidad: 80, deshidratacion: 80 },
    inci: ['agua', 'glicerina', ['escualano', { key: true }], 'alcohol-cetearilico', 'manteca-karite', ['ceramidas', { key: true }], 'colesterol', 'pantenol', 'tocoferol', 'goma-xantana', 'fenoxietanol'],
    texture: 'Crema rica',
    fragranceFree: true,
    shortDescription: 'Crema nutritiva con ceramidas y escualano que repara la barrera de la piel seca y sensible.',
    description: 'Repone los lípidos que pierde la piel seca o irritada: ceramidas, colesterol y escualano, en la proporción de la barrera natural. Calma la tirantez desde la primera aplicación y, con el uso, la piel reacciona menos.',
    whyWeChose: 'Es la crema que recomendamos cuando la piel "está rota": después de un exceso de ácidos, con el frío, o simplemente porque es así. Es rica sin ser grasosa, y no tiene nada de fragancia.',
    ourRating: 94,
    ratingNotes: 'Nuestra crema mejor puntuada. Repara, calma y se tolera muy bien. En piel grasa puede resultar demasiado rica, por eso no la recomendamos para ese tipo de piel.',
    howToUse: 'Mañana y noche, como último paso de la rutina, antes del protector solar de día. En las zonas muy secas podés aplicar una segunda capa fina.',
    precautions: 'No la recomendamos para piel grasa con tendencia a granitos: puede resultar demasiado oclusiva.',
  },
  {
    slug: 'crema-con-peptidos',
    name: 'Crema con péptidos',
    brand: 'verde-raiz',
    stepType: 'MOISTURIZER',
    moment: 'PM',
    sizeLabel: '50 ml',
    priceCents: ars(24_600),
    color: '#EBD9D9',
    avgRating: 4.5,
    reviewCount: 118,
    ideal: ['normal', 'seca'],
    notRecommended: [],
    concerns: { lineas: 80, deshidratacion: 60 },
    inci: ['agua', 'glicerina', 'trigliceridos', 'alcohol-cetearilico', ['peptidos', { key: true }], ['ceramidas', { key: true }], 'escualano', 'tocoferol', 'goma-xantana', 'fenoxietanol'],
    texture: 'Crema sedosa',
    fragranceFree: true,
    shortDescription: 'Crema de noche con péptidos y ceramidas, para la firmeza y las líneas finas.',
    description: 'Una crema de noche que trabaja mientras dormís. Los péptidos le indican a la piel que produzca colágeno y las ceramidas refuerzan la barrera. Es una opción suave para quien quiere cuidar las líneas finas sin usar retinol, o para acompañarlo.',
    whyWeChose: 'No todo el mundo quiere o puede usar retinol. Esta crema es la alternativa que elegimos para esos casos: resultados más lentos, pero sin ninguna irritación.',
    ourRating: 85,
    ratingNotes: 'Textura muy agradable y buena hidratación nocturna. Los péptidos tienen menos evidencia que el retinol, así que los resultados sobre las líneas son más discretos.',
    howToUse: 'De noche, como último paso. Entibiá una pequeña cantidad entre los dedos y aplicala con movimientos hacia arriba, incluido el cuello.',
    precautions: 'Es una crema de noche: debajo del maquillaje, su textura puede resultar pesada.',
  },
  {
    slug: 'fluido-protector-fps-50',
    name: 'Fluido protector FPS 50',
    brand: 'mar-de-sal',
    stepType: 'SUNSCREEN',
    moment: 'AM',
    sizeLabel: '50 ml',
    priceCents: ars(21_500),
    color: '#F2E7C9',
    avgRating: 4.7,
    reviewCount: 356,
    ideal: ['grasa', 'mixta', 'normal'],
    notRecommended: [],
    concerns: { manchas: 80, poros: 30 },
    inci: ['agua', ['filtros-uv', { key: true }], 'dhhb', 'etilhexil-triazona', 'bemotrizinol', ['niacinamida', { key: true }], 'glicerina', 'trigliceridos', 'tocoferol', 'fenoxietanol'],
    texture: 'Fluido liviano',
    fragranceFree: true,
    shortDescription: 'Protector solar fluido FPS 50 de toque seco, para piel mixta y grasa.',
    description: 'Alta protección UVA y UVB en una textura que se absorbe al instante y deja la piel mate. No deja marca blanca y funciona bien debajo del maquillaje. La niacinamida suma control del brillo durante el día.',
    whyWeChose: 'El mejor protector es el que se usa todos los días. Elegimos este porque es el que más gente se pone sin quejarse: no engrasa, no pica en los ojos y no deja la cara blanca.',
    ourRating: 91,
    ratingNotes: 'Textura sobresaliente y muy buena protección. En piel muy seca puede sentirse un poco secante, y para días de playa conviene uno resistente al agua.',
    howToUse: 'Todas las mañanas, como último paso. Aplicá una cantidad generosa (dos dedos de producto para cara y cuello) 15 minutos antes de salir, y reaplicá cada dos horas si estás al sol.',
    precautions: 'Si pasás el día al aire libre, una sola aplicación no alcanza: reaplicá. Evitá el contacto directo con los ojos.',
  },
  {
    slug: 'protector-mineral-fps-50',
    name: 'Protector mineral FPS 50 sensible',
    brand: 'clara-botanica',
    stepType: 'SUNSCREEN',
    moment: 'AM',
    sizeLabel: '50 ml',
    priceCents: ars(23_200),
    color: '#F3DCCD',
    avgRating: 4.6,
    reviewCount: 164,
    ideal: ['sensible', 'seca'],
    notRecommended: [],
    concerns: { sensibilidad: 70, manchas: 70 },
    inci: ['agua', ['filtros-uv', { key: true }], 'oxido-zinc', 'dioxido-titanio', 'trigliceridos', 'glicerina', ['centella', { key: true }], 'bisabolol', 'tocoferol', 'oxido-hierro', 'fenoxietanol'],
    texture: 'Crema fluida con color',
    fragranceFree: true,
    shortDescription: 'Protector mineral FPS 50 con centella, para piel sensible y seca.',
    description: 'Filtros minerales, óxido de zinc y dióxido de titanio, que reflejan la radiación en lugar de absorberla y por eso suelen tolerarse mejor en piel sensible. La centella calma y la base cremosa hidrata. Tiene un tono apenas rosado que evita la marca blanca.',
    whyWeChose: 'En piel sensible, el protector suele ser el paso más difícil: pica, arde o irrita los ojos. Este no. Lo elegimos después de probar varios minerales que dejaban la cara blanca.',
    ourRating: 88,
    ratingNotes: 'Muy buena tolerancia y un acabado mucho más natural que el de la mayoría de los protectores minerales. En pieles muy oscuras puede notarse un leve velo.',
    howToUse: 'Todas las mañanas, como último paso. Aplicá una cantidad generosa y distribuila con toques suaves, sin frotar. Reaplicá cada dos horas si estás al sol.',
    precautions: 'Agitá antes de usar. En piel muy grasa puede dejar un acabado un poco satinado.',
  },
  {
    slug: 'mascarilla-de-arcilla',
    name: 'Mascarilla de arcilla',
    brand: 'mar-de-sal',
    stepType: 'TREATMENT',
    moment: 'PM',
    sizeLabel: '100 g',
    priceCents: ars(15_900),
    color: '#EDD5CB',
    avgRating: 4.4,
    reviewCount: 88,
    ideal: ['grasa', 'mixta'],
    notRecommended: ['seca', 'sensible'],
    concerns: { poros: 70, acne: 40 },
    inci: ['agua', ['arcilla', { key: true }], 'glicerina', ['zinc-pca', { key: true }], 'alcohol-cetearilico', 'pantenol', 'goma-xantana', 'fenoxietanol'],
    texture: 'Pasta cremosa',
    fragranceFree: true,
    shortDescription: 'Mascarilla de caolín y zinc que limpia los poros y deja la piel mate.',
    description: 'Una mascarilla de arcilla blanca que absorbe el exceso de sebo y las impurezas de los poros. El zinc PCA ayuda a regular el brillo en los días siguientes. Se usa una o dos veces por semana, como un reseteo.',
    whyWeChose: 'Es el complemento que más disfrutan las pieles grasas: un ritual corto, con un resultado que se ve al enjuagar. La elegimos porque el caolín es más suave que otras arcillas y no deja la piel tirante.',
    ourRating: 83,
    ratingNotes: 'Efecto inmediato y agradable. Es un complemento, no un tratamiento: no reemplaza al exfoliante ni al sérum. No es apta para piel seca.',
    howToUse: 'Una o dos veces por semana, de noche. Aplicá una capa pareja sobre la piel limpia, evitando ojos y labios, y retirala con agua tibia a los 10 minutos, antes de que se seque del todo.',
    precautions: 'No la dejes secar por completo: tira de la piel y puede irritar. No la uses la misma noche que un exfoliante.',
  },
]
